feat: support extraThisFieldsType(#70)
wechat-miniprogram/glass-easel pull request #155
Opened 2024-05-21 09:17 UTC by gaoachao

Add extraThisFieldsType to enhance type completeness of ComponentInstance, which makes custom properties and methods type safe on "this"
- chaining api only
- on legacy framework need a polyfill which could convert chaining api to mini-program-like api

2024-05-21 10:59 UTC, LastLeaf requested changes

2024-05-21 10:59 UTC, LastLeaf commented on glass-easel-miniprogram-adapter/src/behavior.ts
> +    inner: glassEasel.Behavior<TData, TProperty, TMethod, TChainingFilter, TDelayedData>,
This name is not straightforward.

2024-05-21 10:59 UTC, LastLeaf commented on glass-easel-miniprogram-adapter/src/builder/base_behavior_builder.ts
> +  TDelayedData extends DataList = Empty,
The argument order should be aligned with `Behavior` .

2024-05-21 10:59 UTC, LastLeaf commented on glass-easel-miniprogram-template/src/components/image/image.ts
> +})
This change?

2024-05-21 11:02 UTC, gaoachao commented on glass-easel-miniprogram-adapter/src/behavior.ts
> +    inner: glassEasel.Behavior<TData, TProperty, TMethod, TChainingFilter, TDelayedData>,
what about TExtraThisData ?

2024-05-23 08:27 UTC, LastLeaf commented on glass-easel-miniprogram-adapter/src/behavior.ts
> +    inner: glassEasel.Behavior<TData, TProperty, TMethod, TChainingFilter, TDelayedData>,
`TExtraThisFields`

2024-05-24 06:34 UTC, LastLeaf approved these changes

2024-05-24 06:35 UTC, LastLeaf commented
This contains changes about some critical types. Delay this merge to about v0.6.

2024-05-27 11:26 UTC, merged